# Generated by Django 6.0.5 on 2026-06-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrowrecord_return_date_borrowrecord_returned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_borrowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='return_date',
        ),
    ]
