# Generated by Django 6.0.5 on 2026-06-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_book_remove_borrowrecord_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='book_id',
        ),
        migrations.AddField(
            model_name='book',
            name='book_code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='borrow.book'),
            preserve_default=False,
        ),
    ]
