# Generated by Django 6.0.5 on 2026-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_remove_borrowrecord_book_id_book_book_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_code',
            field=models.CharField(max_length=50),
        ),
    ]
